config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    root to: "devise/sessions#new"
  end

  get 'dispatcher/panel' => 'dispatchers#index'

  get 'search' => 'dispatchers#search'
  post 'search' => 'dispatchers#search'

  get 'change_order' => 'dispatchers#change_order'
  get 'dispatcher/icons' => 'dispatchers#icon'
  get 'render_icons' => 'map_markers#render_icons'

  post 'create_map_marker' => 'map_markers#create'
  get 'create_map_marker' => 'map_markers#create'

  get 'create_map_geo_object' => 'map_geo_objects#create'
  post 'create_map_geo_object' => 'map_geo_objects#create'

  get 'destroy_map_marker' => 'map_markers#destroy'

  #
  #

  get 'admin/home' => 'admins#index'
  get 'create_car' => 'admins#create_car'
  post 'create_car' => 'admins#create_car'

  post 'create_order' => 'orders#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_one :user
  belongs_to :parking
  acts_as_list
end

app/models/map_geo_object.rb
class MapGeoObject < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search, against: :address, using: { tsearch: { any_word: true, prefix: true } }

end

app/models/map_marker.rb
class MapMarker < ActiveRecord::Base
  mount_uploader :icon, IconUploader
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/parking.rb
class Parking < ActiveRecord::Base
  has_many :cars
end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :car
  devise :database_authenticatable,
         :trackable, :validatable

  validates :username, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!, :is_admin?
  def index

  end

  def create_car
    @car = Car.create car_params

    respond_to do |format|
      format.js
    end
  end

  private

  def car_params
    params.permit(:rate, :name)
        #.merge(status: current_user)
  end

  def is_admin?
    unless current_user && current_user.role == "admin"
      flash[:error] = "У вас недостаточно прав для просмотра!"
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    if current_user.role == "dispatcher"
      dispatcher_panel_path
    elsif current_user.role == "driver"
      driver_home_path
    elsif current_user.role == "admin"
      admin_home_path
    end
  end
end

app/controllers/dispatchers_controller.rb
class DispatchersController < ApplicationController
  before_action :authenticate_user!, :is_dispatcher?
  def index
=begin
    , bounds: [[47.961315, 37.813755], [48.128684, 38.110756]]
strictBounds: true
=end

=begin
    p results = Geocoder.search('макеевка Солнечный 11')
=end

=begin
    Geocoder.configure(lookup: :google)
    p results = Geocoder.search('донецк ильича 32', bounds: [[47.961315, 37.813755], [48.128684, 38.110756]])
=end
    @markers = MapMarker.all
    @objects = MapGeoObject.all
    @cars = Car.all
    @parkings = Parking.all
    @polygones = Polygon.all
  end

  def search
    if params[:term]
      p params[:term]
      @result = MapGeoObject.search(params[:term])
      @results = []
      @result.each do |result|
        @results << {latitude: result.latitude, longitude: result.longitude,
                     address: result.address, icon: 'base'}
      end

      Geocoder.configure(lookup: :yandex)
      results = Geocoder.search(params[:term], params: {results: 5})
      results.try(:each)do |res|
        if res.country == 'Украина'
          @results << {latitude: res.coordinates[0], longitude: res.coordinates[1],
                       address: res.address.split(', ').reverse.join(", "), icon: 'yandex'}
        end
      end


        response = HTTParty.get(URI.parse(URI.escape"http://openstreetmap.ru/api/search?q=#{params[:term]}"))
        response = JSON.parse(response)
        response['matches'].try(:each) do |res|
        @results << {latitude: res["lat"], longitude: res["lon"],
                     address: res["display_name"].split(', ').reverse.join(", "), icon: 'world'}
        end

        Geocoder.configure(lookup: :nominatim)
        results = Geocoder.search(params[:term], params: {language: :ru})
        results.try(:each)do |res|
          if res.country == 'Украина'
            @results << {latitude: res.coordinates[0], longitude: res.coordinates[1],
                         address: res.address, icon: 'world2'}
          end
        end

      respond_to do |format|
        format.js
      end

    end



  end

  def change_order
    car = Car.find(params["car_id"])
    car.set_list_position(params["position"])
    @parking = Parking.find(params["park_id"])

    respond_to do |format|
      format.js
    end
  end

  def icon
    @markers = MapMarker.all
  end

  private
  def is_dispatcher?
    unless current_user && current_user.role == "dispatcher"
      flash[:error] = "У вас недостаточно прав для просмотра!"
      redirect_to root_path
    end
  end


end

app/controllers/map_geo_objects_controller.rb
class MapGeoObjectsController < ApplicationController

  def create
    @object = MapGeoObject.create map_geo_object_params
    @objects = MapGeoObject.all
    @polygones = Polygon.all
    @markers = MapMarker.all
    respond_to do |format|
      format.js
    end
  end

  private

  def map_geo_object_params
    params.require(:map_geo_object).permit(:icon, :latitude, :longitude, :address)
  end

end

app/controllers/map_markers_controller.rb
class MapMarkersController < ApplicationController

  def create
    @icon = MapMarker.new(icon: params[:file], name: (0...8).map { (65 + rand(26)).chr }.join)
    if @icon.save!
      respond_to do |format|
        format.json{ render :json => @icon }
      end
    end
  end

  def render_icons
    @markers = MapMarker.all
    respond_to do |format|
      format.js
    end
  end

  def destroy
    marker = MapMarker.find(params[:id])
    marker.destroy!
    @markers = MapMarker.all
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
      when 'success'
        'alert-success'
      when 'error'
        'alert-danger'
      when 'alert'
        'alert-warning'
      when 'notice'
        'alert-info'
      else
        flash_type.to_s
    end
  end

  def search_icon(name)
    marker = MapMarker.where(name: name).last
    marker.icon.url if marker
  end
end

app/helpers/dispatchers_helper.rb
module DispatchersHelper
end

app/views/admins/create_car.js.erb
<% publish_to "/cars" do %>
  $('#allCars').prepend(" <%= j render(@car) %> ");
<% end %>

$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Внимание!',
        message:'тачка поехала',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

app/views/admins/index.html.erb
<div class="wrapper">
  <!-- Sidebar  -->

  <%= render 'layouts/left_navbar' %>
  <!-- Page Content  -->
  <div id="content" style=" width: 100%">

    <%= render 'layouts/navbar' %>
    <div class="container-fluid" style="margin-top: 30px">
      <div class="row">
        <div class="col-12">
          <div class="card" style="padding-left: 15px; padding-right: 15px">
            <div class="card-header">
              <h5>Добавить водителя</h5>
              <span style="color: rgba(255,255,255,.62); font-size: .875rem;">...</span>
            </div>
            <br>
            <%= form_tag create_car_path, method: :post, remote: true do %>

                <div class="form-row">
                  <div class="col">
                    <div class="input-group">
                      <div class="group" style="width: 100%; margin-top: 0">
                        <input type="text" name="name" required="required" autocomplete="off" spellcheck="false"/>
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        <label>Позывной</label>
                      </div>
                    </div>
                  </div>
                  <div class="col">
                    <select id="tarif" name="rate">
                      <option value="Стандарт">Стандарт</option>
                      <option value="Эконом">Эконом</option>
                      <option value="Премиум">Премиум</option>
                    </select>
                  </div>
                </div>
                <button type="submit" class="btn dropzone-button">Добавить</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $('#tarif').select2({
        minimumResultsForSearch: -1,
        language: "ru-RU",
        width: '100%'
    });
</script>

app/views/cars/_car.html.erb
<div class="badge badge-warning car">
  <p style="margin: 0"><%= @car.name %></p>
  <span>tes</span>
</div>

app/views/dispatchers/_addresses.html.erb
<div style="max-height: 65vh; overflow-y: auto">
  <% results.each do |result| %>
      <div class="demo-solution demo-solution--flexbox addresses-scope" style="border-top: 1px solid hsla(0,0%,71%,.2); margin-bottom: 2px">

        <% if result[:icon] == 'yandex'%>
            <i class="fa fa-yahoo" style="color: red; padding-left: 1.115rem; padding-right: 1.115rem;"></i>
        <% elsif result[:icon] == 'world'%>
            <i class="fa fa-globe fa-lg" style="padding-left: 0.975rem"></i>
        <% elsif result[:icon] == 'world2'%>
            <i class="fa fa-ravelry fa-lg" style="color: mediumpurple; padding-left: 0.575rem"></i>
      <% else %>
            <!--<i class="material-icons" style="color: #b2b2b2">home</i>-->
            <!--<i class="fa fa-wordpress fa-flip-vertical" style="color: red; padding-left: 0.475rem"></i>-->
            <sup class="maxim" style="padding-left: 0.425rem; padding-top: 1rem">Maxim</sup>
        <% end %>
        <input name="longtitude" class="lon" type="hidden" value="<%= result[:longitude]%>">
        <input name="latitude" class="lat" type="hidden" value="<%= result[:latitude]%>">
        <span style="padding: 0.375rem 0.75rem;"><%=result[:address]%></span>
      </div>
  <% end %>
</div>



app/views/dispatchers/_cars_table.html.erb

<div id="table-content" style="height: 75vh; overflow-y: auto;">

<table class="table table-sm no-border" id="parkingTable">
  <thead>
  <tr style="display: none">
    <th></th>
    <th></th>
    <th></th>

  </tr>
  </thead>
  <tbody>

  <% parkings.each do |park| %>
      <tr>
        <td><small><%= park.name%></small></td>
        <td><%=park.cars.count%></td>
        <td>

          <div class="sortable" id="<%=park.id%>">
            <% park.cars.order('position').each do|car| %>
                <div class="badge badge-warning car custom-dropdown" data-id="<%= car.id %>">
                  <p style="margin: 0"><%=car.id%></p>
                  <span>tes</span>
                  <div id="car<%= car.id %>" class="dropdown-content">
                    <a class="dropdown-inner" href="#">Отправить вне очереди</a>
                    <a class="dropdown-inner" href="#">Поменять парковку</a>
                    <a class="dropdown-inner" href="#">Показать на карте</a>
                  </div>
                </div>
            <% end %>
          </div>

        </td>
      </tr>
  <% end %>
  <td><small>Гараж</small></td>
  <td><%=cars.count%></td>
  <td id="allCars">
    <%cars.each do|car| %>
        <div class="badge badge-warning car car-garaj">
          <p style="margin: 0">123</p>
          <span>tes</span>
        </div>
    <% end %>
  </td>
  </tbody>
</table>
</div>



<script>
    $(document).ready( function () {

        $(".sortable").sortable({
            revert: true,
            start: function (event, ui) {
                ui.item.data('start_pos', ui.item.index());
                ui.placeholder.width(ui.item.width());
                ui.placeholder.css('visibility', 'visible');
            },
            stop: function(event, ui) {
                var start_pos = ui.item.data('start_pos');
                if (start_pos != ui.item.index()) {
                    var park_id = ui.item.parent().attr('id');
                    $.ajax({
                        url: "<%= change_order_path %>",
                        type: "GET",
                        data: { position: ui.item.index()+1, car_id: ui.item.data("id"), park_id: park_id}

                    })
                }
            }
        });

        $(".car").each(function() {
           $(this).on('contextmenu', function(e) {
               $(".dropdown-content").each(function () {
                  $(this).removeClass('show');
               });
               e.preventDefault();
               var id = 'car' + $(this).data("id");
               var row = $('#' + id);
               row.addClass("show");
               var width = row.width() - $(this).width()*1.77;
               row.css('margin-left',-width);
           })
        });

        $(window).on('click mouseup mousedown', function(e) {
            if (!e.target.matches('.dropdown-inner')) {
              $(".dropdown-content").each(function () {
                  $(this).removeClass('show');
              });
            }
        });

        $('#parkingTable').dataTable({
            autoWidth: false,
            pagingType: 'simple_numbers',
            scrollCollapse: true,
            /*            processing: true,*/
            responsive: false,
            "info": false,
            "ordering": false,
            "bPaginate": false,
            "bStateSave": true,
            "fnStateSave": function (oSettings, oData) {
                localStorage.setItem('offersDataTables', JSON.stringify(oData));
            },
            "fnStateLoad": function (oSettings) {
                return JSON.parse(localStorage.getItem('offersDataTables'));

            },

            "columnDefs": [{
                "targets": [],
                "orderable": false
            }],

            "language": {
                "sProcessing": "Подождите...",
                "sLengthMenu": "Показать _MENU_ записей",
                "sZeroRecords": "Записи отсутствуют.",
                "sEmptyTable": "В таблице отсутствуют данные",
                "sInfo": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "sInfoEmpty": "Записи с 0 до 0 из 0 записей",
                "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
                "sInfoPostFix": "",
                "sSearch": "",
                "sUrl": "",
                "searchPlaceholder": "Поиск...",
                "sInfoThousands": ",",
                "sLoadingRecords": "Загрузка записей...",
                "oPaginate": {
                    "sFirst": "Первая",
                    "sLast": "Последняя",
                    "sNext": "Следующая",
                    "sPrevious": "Предыдущая"
                },
                "oAria": {
                    "sSortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sSortDescending": ": активировать для сортировки столбца по убыванию"
                }
            }

        });

        var el = $('#parkingTable_wrapper').children(".row:first-child");
            el.children(".col-sm-12:nth-child(1)").remove();
            el.children(".col-sm-12:nth-child(1)").removeClass('col-sm-12 col-md-6').addClass('col-md-12 table-no-padding');

        $('.dataTables_filter input').addClass('form-control');

        $('#table-content').mCustomScrollbar({
            axis: 'y',
            theme: 'minimal'
        });

    });

</script>

<%= subscribe_to "/cars" %>

app/views/dispatchers/_map.html.erb
<div id="map" style="height: 84.5vh"></div>

<script>
    $(document).ready(function() {

        var map;

        map = L.map('map', { zoomControl:false }).setView([48.047974, 37.964475], 14);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors for TaxiMaxim'
        }).addTo(map);

/*        map = L.map('map', {attributionControl: false});
        map.setView([48.047974, 37.964475], 13);
        L.control.attribution({prefix:''}).addAttribution('<a href="http://maps.sputnik.ru/">Спутник</a> | &copy; Ростелеком | &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>').addTo(map);
        L.tileLayer('http://tiles.maps.sputnik.ru/{z}/{x}/{y}.png', {
            maxZoom: 19
        }).addTo(map);*/

/*        map = L.map('map', { zoomControl:false }).setView([48.047974, 37.964475], 20);
            L.tileLayer('http://vec{s}.maps.yandex.net/tiles?l=map&v=4.55.2&z={z}&x={x}&y={y}&scale=2&lang=ru_RU', {
                subdomains: ['01', '02', '03', '04'],
                attribution: '<a http="yandex.ru" target="_blank">Яндекс</a>',
                reuseTiles: true,
                updateWhenIdle: false
            }
        ).addTo(map);*/


        var polygones_array = [];
        <% polygones.try(:each) do |polygone| %>
          var latlngs = <%=polygone.coordinates%>;
          var polygon = L.polygon(latlngs, {color: '<%=polygone.color%>'}).addTo(map);
          polygon.bindTooltip("<%=polygone.name%> <%=polygone.cost if polygone.cost%>",
              {permanent: true, direction:"center"}
          ).openTooltip();
          polygones_array.push(polygon);

        <% end %>

        map.on('moveend ', function() {
            var currentPos = map.getCenter();
            var lat = currentPos.lat;
            var lng = currentPos.lng;
            localStorage.setItem('lat', lat);
            localStorage.setItem('lng', lng);
        });

        map.on('zoomend', function() {
            zoom = map.getZoom();
            localStorage.setItem('zoom', zoom);
        });

        function drawMarkers() {
            var objects_group = new L.LayerGroup();
            <% objects.try(:each) do |marker| %>
            var greenIcon = L.icon({
                iconUrl: '<%=search_icon(marker.icon)%>',
                //shadowUrl: 'leaf-shadow.png',
                iconSize:     [30, 30], // size of the icon
                shadowSize:   [50, 64], // size of the shadow
                iconAnchor:   [15, 0], // point of the icon which will correspond to marker's location
                //shadowAnchor: [4, 62],  // the same for the shadow
                //popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
            });
            marker = L.marker([<%=marker.latitude%>, <%=marker.longitude%>], {icon: greenIcon})
                .bindPopup('<%=marker.address%>');
            marker.addTo(objects_group);
            <% end %>
            objects_group.addTo(map);
        }

        drawMarkers();

        map.on('contextmenu', function(e) {
            alert("Lat, Lon : " + e.latlng.lat + ", " + e.latlng.lng);

            popup = L.popup();
            popup.setLatLng(e.latlng);
            popup.setContent(
                '<%= form_tag create_map_geo_object_path, method: :post, remote: true do %>' +
                '<h6>Добавить адрес</h6>' +
                '<span>Выберите иконку</span>' +
                '<div class="cc-selector">' +
                  <% markers.try(:each) do |marker| %>
                    '<input id="<%=marker.name%>" type="radio" name="map_geo_object[icon]" value="<%=marker.name%>" /> ' +
                    '<label style="background-image:url(<%=marker.icon.url%>);" class="drinkcard-cc" for="<%=marker.name%>"></label> ' +
                  <% end %>
                '</div>' +
                '<div class="group" style="margin-top: 20px">' +
                '<input type="text" name="map_geo_object[address]" required="required" autocomplete="off" spellcheck="false"/>' +
                '<span class="highlight"></span>' +
                '<span class="bar"></span>' +
                '<label>Введите название</label>' +
                '</div>' +
                '<input name="map_geo_object[latitude]" type="hidden" value=' + e.latlng.lat + ' >' +
                '<input name="map_geo_object[longitude]" type="hidden" value=' + e.latlng.lng + ' >' +
                '<button type="submit" class="btn btn-login btn-block">Готово</button>' +
                '<% end %>');
            popup.openOn(map);
        });


        $(window).on('resize', function () {
            map.invalidateSize();
        })

        var search_group = new L.LayerGroup();
        var markers_array = [];

        $('#addresses').on('search', function() {
            $('.addresses-scope').each(function() {
                var me = $(this).children("span");
                var t = me.text();
                t = t.replace(/^[^,]+/, function(v) {
                    return "<b class='class1'>" + v + "</b>";
                });
                t = t.replace(', Донецкая область, Украина', '');
                t = t.replace(', Донецкая область, 86100-86180, Украина', '');
                me.html(t);
                $(this).on('click', function () {
                    console.log(me.text())
                    var place = $(this).children("span").text();
                    var lon = $(this).children(".lon").val();
                    var lat = $(this).children(".lat").val();
                    $('#addresses').addClass('d-none');
                    $('.search-button').toggleClass('d-none');
                    $('#term').val($('#term').data("prefix") + place);
                    map.setView(new L.LatLng(lat, lon), 16);
                    marker = new L.Marker([lat, lon]);
                    markers_array.push(marker);
                    marker.addTo(search_group);
                    if (markers_array.length > 1) {
                        search_group.removeLayer(markers_array[0]);
                        markers_array.shift();
                    }
                    search_group.addTo(map);

                    var result_array = [];
                    $.each(polygones_array, function(index, poly){

                        var inside = false;
                        var x = marker.getLatLng().lat, y = marker.getLatLng().lng;
                        for (var ii=0;ii<poly.getLatLngs().length;ii++){
                            var polyPoints = poly.getLatLngs()[ii];
                            for (var i = 0, j = polyPoints.length - 1; i < polyPoints.length; j = i++) {
                                var xi = polyPoints[i].lat, yi = polyPoints[i].lng;
                                var xj = polyPoints[j].lat, yj = polyPoints[j].lng;
                                var intersect = ((yi > y) != (yj > y))
                                    && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
                                if (intersect) inside = !inside;
                            }
                        }

                        /*if (inside) console.log(poly.getTooltip()._content);*/
                        if (inside) {
                            result_array.push(poly.getTooltip()._content);
                            console.log(result_array[result_array.length-1])
                            /*$('#additional').val(result_array[result_array.length-1])*/
                            $('#additional').text(result_array[result_array.length-1])
                        }


                    });
                });

            });
        });

        $('#map').on('test', function() {
            /*$(".leaflet-popup-close-button")[0].click();*/
            /*map.panTo(new L.LatLng(localStorage.getItem('lat'), localStorage.getItem('lng')));*/
            map.panTo([
                localStorage.getItem('lat'),
                localStorage.getItem('lng')
            ]).setZoom(localStorage.getItem('zoom'));
        });

    });

</script>

<%= subscribe_to "/map" %>

app/views/dispatchers/change_order.js.erb
$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Внимание!',
        message:'поменяли ордер',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

<% publish_to "/cars" do %>
  $('#<%=@parking.id%>').html(
    '  <% @parking.cars.order('position').each do|car| %>'+
    '    <div class="badge badge-warning car custom-dropdown" data-id="<%= car.id %>">'+
    '      <p style="margin: 0"><%=car.id%></p>'+
    '      <span>tes</span>'+
    '      <div id="car<%= car.id %>" class="dropdown-content">'+
    '        <a class="dropdown-inner" href="#">Отправить вне очереди</a>'+
    '        <a class="dropdown-inner" href="#">Поменять парковку</a>'+
    '        <a class="dropdown-inner" href="#">Показать на карте</a>'+
    '      </div>'+
    '    </div>'+
    '  <% end %>')

    $(".car").each(function() {
        $(this).on('contextmenu', function(e) {
            $(".dropdown-content").each(function () {
                $(this).removeClass('show');
            });
            e.preventDefault();
            var id = 'car' + $(this).data("id");
            var row = $('#' + id);
            row.addClass("show");
            var width = row.width() - $(this).width()*1.77;
            row.css('margin-left',-width);
        })
    });
<% end %>

app/views/dispatchers/icon.html.erb
<div class="wrapper">
  <!-- Sidebar  -->

  <%= render 'layouts/left_navbar' %>

  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%">

    <%= render 'layouts/navbar' %>

    <div class="container-fluid" style="margin-top: 50px">

      <div class="col-12">
        <div class="card" style="padding: 15px">

          <div class="card-header">
            <h5>Загрузка иконок</h5>
            <span style="color: rgba(255,255,255,.62); font-size: .875rem;">Загруженные сюда иконки будут отображаться на карте</span>
          </div>

          <br>


          <%= form_tag create_map_marker_path, method: :post, class: "dropzone", id: "media-dropzone" do %>
              <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
              <div class="dz-message" data-dz-message>
                <span>Перетащите файлы сюда для загрузки или </span>
                <div class="btn dropzone-button">Выбрать файлы</div>
              </div>
              <div class="fallback">
                <%= file_field_tag "icon", multiple: true%>
              </div>
          <% end %>

          <h5>Загруженные файлы:</h5>

          <div id="icons" class="d-flex flex-wrap">
            <%= render 'map_markers/markers_container', markers: @markers%>
          </div>

        </div>
      </div>


    </div>

  </div>
</div>

<script>

    Dropzone.autoDiscover = false;
    $("#media-dropzone").dropzone({
        init: function() {
            this.on("success", function(file, responseText) {
                $.ajax({
                    url: "<%= render_icons_path %>",
                    type: "GET"
                });
            });
        }
    });

</script>

app/views/dispatchers/search.js.erb
$('#addresses').html("<%= j render(:partial => 'addresses', :locals => {results: @results}) %>").trigger('search');


app/views/layouts/_left_navbar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
    <h3 class="maxim"><span style="color: black">Taxi</span><b>MAXIM</b></h3>
    <strong>BS</strong>
  </div>

  <% if current_user.role == "dispatcher" %>

  <ul class="list-unstyled components">
    <li class="<%= 'active' if current_page?(dispatcher_panel_path) %>">
      <%= link_to root_path do%>
        <i class="fa fa-home"></i>
        <span>Главная</span>
      <% end %>
    </li>
    <li class="<%= 'active' if current_page?(dispatcher_icons_path) %>">
      <%= link_to dispatcher_icons_path do%>
          <i class="fa fa-picture-o"></i>
        <span>Иконки</span>
      <% end %>
    </li>
  </ul>

  <% elsif current_user.role == "admin"%>
      <ul class="list-unstyled components">
        <li class="<%= 'active' if current_page?(admin_home_path) %>">
          <%= link_to root_path do%>
              <i class="fa fa-home"></i>
              <span>Главная</span>
          <% end %>
        </li>
      </ul>
  <% end %>

</nav>

app/views/map_markers/_markers_container.html.erb
<%markers.each do |marker|%>
    <div class="image-container" style="position: relative">
      <img src="<%=marker.icon.url %>" height="75" width="75" style="margin: 5px 10px 10px">

      <%= link_to destroy_map_marker_path(id: marker.id), title: 'Удалить',
                  class: 'small-delete-button text-center', remote: true do %>
          <i class="fa fa-times" style="margin-top: 8px"></i>
      <% end %>

    </div>
<% end %>

app/views/map_markers/destroy.js.erb
$('#icons').html("<%= j render(:partial => 'map_markers/markers_container', :locals => {markers: @markers}) %>")

app/views/map_markers/render_icons.js.erb
$('#icons').html("<%= j render(:partial => 'map_markers/markers_container', :locals => {markers: @markers}) %>")